import { RegionId, RegionInfo } from './types';

export const REGIONS: Record<RegionId, RegionInfo> = {
  lumen_village: {
    id: 'lumen_village',
    name: 'Vila de Lumen',
    subtitle: 'O Refúgio Silencioso',
    description: 'Um assentamento esquecido esculpido na rocha calcária superior. Antigas lanternas de ressonância ainda crepitam suavemente, acolhendo os poucos que ainda guardam memórias do mundo de cima.',
    primaryColor: '#6ee7b7',
    ambientColors: ['#0f172a', '#1e293b', '#334155'],
    fogColor: 'rgba(30, 41, 59, 0.4)',
    bgParticles: 'ash',
  },
  echo_forest: {
    id: 'echo_forest',
    name: 'Bosque do Eco',
    subtitle: 'Raízes Luminescentes',
    description: 'Cavernas imensas tomadas por fungos gigantes e lianas que vibram em frequências musicais. O ar é denso com esporos brilhantes que respondem aos passos dos viajantes.',
    primaryColor: '#38bdf8',
    ambientColors: ['#042f2e', '#0f3d3e', '#115e59'],
    fogColor: 'rgba(4, 47, 46, 0.45)',
    bgParticles: 'spores',
  },
  varron_mines: {
    id: 'varron_mines',
    name: 'Minas de Varron',
    subtitle: 'Engrenagens Esquecidas',
    description: 'Escavações de cobre e bronze onde os antigos habitantes de Echoward perfuraram a crosta em busca dos veios puros de Ressonância. As esteiras mecânicas agora descansam em silêncio.',
    primaryColor: '#f97316',
    ambientColors: ['#291809', '#431407', '#1c1917'],
    fogColor: 'rgba(67, 20, 7, 0.4)',
    bgParticles: 'steam',
  },
  submerged_city: {
    id: 'submerged_city',
    name: 'Cidade Submersa',
    subtitle: 'Arquivos Afogados',
    description: 'Avenidas de pedra e pontes em arco parcialmente engolidas por águas subterrâneas límpidas. Espectros aquáticos vagam pelas bibliotecas cujas páginas foram petrificadas pelo tempo.',
    primaryColor: '#2dd4bf',
    ambientColors: ['#082f49', '#0c4a6e', '#1e1b4b'],
    fogColor: 'rgba(12, 74, 110, 0.45)',
    bgParticles: 'bubbles',
  },
  dead_gardens: {
    id: 'dead_gardens',
    name: 'Jardins Mortos',
    subtitle: 'A Espinheira Real',
    description: 'Jardins outrora exuberantes, criados pela realeza subterrânea para simular a primavera do mundo exterior. Hoje, espinhos venenosos e pétalas desbotadas protegem segredos proibidos.',
    primaryColor: '#c084fc',
    ambientColors: ['#2e1065', '#3b0764', '#18181b'],
    fogColor: 'rgba(59, 7, 100, 0.4)',
    bgParticles: 'petals',
  },
  broken_cathedral: {
    id: 'broken_cathedral',
    name: 'Catedral Quebrada',
    subtitle: 'Santuário do Silêncio',
    description: 'Uma monumental basílica subterrânea erguida para homenagear os Primeiros Ressonantes. Vitrais despedaçados refletem o dourado envelhecido e o carmesim dos rituais esquecidos.',
    primaryColor: '#f59e0b',
    ambientColors: ['#450a0a', '#18181b', '#292524'],
    fogColor: 'rgba(69, 10, 10, 0.45)',
    bgParticles: 'ash',
  },
  tower_of_voices: {
    id: 'tower_of_voices',
    name: 'Torre das Vozes',
    subtitle: 'Os Tubos Ressonantes',
    description: 'Um vão vertical vertiginoso por onde passam correntes de ar que ativam imensos órgãos de pedra. Sussurros de eras passadas ecoam nas escadarias suspensas.',
    primaryColor: '#93c5fd',
    ambientColors: ['#1e1b4b', '#1e293b', '#0f172a'],
    fogColor: 'rgba(30, 27, 75, 0.4)',
    bgParticles: 'resonance',
  },
  ash_fields: {
    id: 'ash_fields',
    name: 'Campos de Cinza',
    subtitle: 'Dunas dos Esquecidos',
    description: 'Planícies cinzentas onde restos pulverizados de antigas estruturas formam dunas silenciosas. Soldados petrificados em postura de combate marcam as antigas linhas de defesa.',
    primaryColor: '#94a3b8',
    ambientColors: ['#18181b', '#27272a', '#3f3f46'],
    fogColor: 'rgba(24, 24, 27, 0.5)',
    bgParticles: 'ash',
  },
  drowned_palace: {
    id: 'drowned_palace',
    name: 'Palácio Afogado',
    subtitle: 'Trono Subterrâneo',
    description: 'Colunas de mármore dourado e afrescos desgastados sob tetos gotejantes. Os aposentos reais permanecem intocados, aguardando ordens que jamais retornarão.',
    primaryColor: '#38bdf8',
    ambientColors: ['#0f172a', '#1e3a8a', '#1e293b'],
    fogColor: 'rgba(30, 58, 138, 0.45)',
    bgParticles: 'bubbles',
  },
  ner_abyss: {
    id: 'ner_abyss',
    name: 'Abismo de Ner',
    subtitle: 'O Vazio Sem Ecos',
    description: 'Uma escuridão quase absoluta nas camadas mais profundas de Echoward. A Ressonância aqui não canta — ela devora. Apenas os olhos luminescentes e partículas brancas revelam o caminho.',
    primaryColor: '#818cf8',
    ambientColors: ['#020617', '#030712', '#09090b'],
    fogColor: 'rgba(2, 6, 23, 0.75)',
    bgParticles: 'void',
  },
  ancient_nursery: {
    id: 'ancient_nursery',
    name: 'Berçário Antigo',
    subtitle: 'Casulos das Máscaras',
    description: 'Câmaras repletas de receptáculos de porcelana e âmbar ressonante. Foi aqui que criaturas como Nox foram geradas para abrigar a consciência das cinzas.',
    primaryColor: '#fed7aa',
    ambientColors: ['#1c1917', '#292524', '#0c0a09'],
    fogColor: 'rgba(28, 25, 23, 0.5)',
    bgParticles: 'resonance',
  },
  echoward_core: {
    id: 'echoward_core',
    name: 'Coração de Echoward',
    subtitle: 'Epicentro do Silêncio',
    description: 'O nexo colossal de cristais ressonantes onde O Silêncio teve início. Aqui, o espaço dobra sobre si mesmo e ecos de todas as eras convergem em um canto infinito.',
    primaryColor: '#67e8f9',
    ambientColors: ['#083344', '#164e63', '#042f2e'],
    fogColor: 'rgba(8, 51, 68, 0.5)',
    bgParticles: 'resonance',
  },
};
